server:
  port: 7301
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 服务名称
    name: eureka-consumer
# 服务注册与发现相关配置
eureka:
  client:
    # 注册中心地址
    serviceUrl:
      defaultZone: http://peer1:7101/eureka/,http://peer2:7102/eureka/
#启用断路器，spring-cloud-starter-openfeign已经自带了Hystrix
feign:
  hystrix:
    enabled: true